<form method=post action="<?php echo $this->getUrl('*/*/process') ?>">

    <?php if (count($this->error)) : ?>
        <div class="error">
            Please correct following errors:
            <ul>
                <li><?php echo implode('</li><li>', $this->error); ?></li>
            </ul>
        </div>
    <?php endif; ?>

    <table width="632" cellpadding="2" cellspacing="2">
        <tr<?php echo is_array($this->error) && isset($this->error['admin_email']) ? ' class="error"' : '' ?>>
            <td align="right"><label for="admin_email">Administrator E-Mail:</label></td>
            <td><input name="admin_email" id="admin_email" size="50" value="<?php echo $this->options['authentication']['email'] ?>"/></td>
        </tr>
        <tr<?php echo is_array($this->error) && isset($this->error['admin_password']) ? ' class="error"' : '' ?>>
            <td align="right"><label for="admin_password">Administator Password:</label></td>
            <td><input type="password" name="admin_password" id="admin_password" size="50" value="<?php echo $this->options['authentication']['password'] ?>"/></td>
        </tr>
        <tr<?php echo is_array($this->error) && isset($this->error['default_from']) ? ' class="error"' : '' ?>>
            <td align="right"><label for="default_from">Default From Address:</label></td>
            <td><input name="default_from" id="default_from" size="50" value="<?php echo $this->options['settings']['default_from'] ?>"/></td>
        </tr>
        <tr<?php echo is_array($this->error) && isset($this->error['db_host']) ? ' class="error"' : '' ?>>
            <td align="right"><label for="db_host">Database Host:</label></td>
            <td><input name="db_host" id="db_host" value="<?php echo $this->options['resources']['db']['params']['host'] ?>" size="50"/></td>
        </tr>
        <tr<?php echo is_array($this->error) && isset($this->error['db_user']) ? ' class="error"' : '' ?>>
            <td align="right"><label for="db_user">Database User Name:</label></td>
            <td><input name="db_user" id="db_user" value="<?php echo $this->options['resources']['db']['params']['username'] ?>" size="50"/></td>
        </tr>
        <tr>
            <td align="right"><label for="db_password">Database User Password:</label></td>
            <td><input type="password" name="db_password" id="db_password" value="<?php echo $this->options['resources']['db']['params']['password'] ?>" size="50"/></td>
        </tr>
        <tr<?php echo is_array($this->error) && isset($this->error['db_name']) ? ' class="error"' : '' ?>>
            <td align="right"><label for="db_name">Database Name:</label></td>
            <td><input name="db_name" id="db_name" value="<?php echo $this->options['resources']['db']['params']['dbname'] ?>" size="50"/></td>
        </tr>
        <tr>
            <td align="right"><label for="db_prefix">Database Table Prefix:</label></td>
            <td><input name="db_prefix" id="db_prefix" value="<?php echo $this->options['resources']['db']['params']['prefix'] ?>" size="50"/></td>
        </tr>
        <tr<?php echo is_array($this->error) && isset($this->error['keep_history']) ? ' class="error"' : '' ?>>
            <td align="right"><label for="keep_history">Show timeline for last:</label></td>
            <td><input type="text" name="keep_history" id="keep_history" value="<?php echo $this->options['settings']['keep_history'] ?>" size="3"/> days</td>
        </tr>
        <tr>
            <td align="right"><label for="alchemy_api_key">Alchemy API Key (<a href="http://www.alchemyapi.com/api/register.html" target="_blank">Get It Here</a>):</label></td>
            <td><input type="text" name="alchemy_api_key" id="alchemy_api_key" value="<?php echo $this->options['settings']['alchemy_api_key'] ?>" size="50"/></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Save Settings" class="bu"/></td>
        </tr>
    </table>

</form>