<table cellspacing="0" cellpadding="0" bgcolor="#E4E4DD">
    <tr><td><img src="<?php echo $this->baseUrl('images/a12.gif') ?>" alt=""/></td>
        <td background="<?php echo $this->baseUrl('images/a13.gif') ?>"></td>
        <td><img src="<?php echo $this->baseUrl('images/a15.gif') ?>" alt=""/></td></tr>
    <tr><td></td><td style="padding:5px;">

<form method="post" action="<?php echo $this->getUrl('login/index/process') ?>">
    <table>
        <tr><td><label for="email">E-Mail:</label></td><td><input name="email" id="email" type="text"/></td></tr>
        <tr><td><label for="password">Password:</label></td><td><input name="password" id="password" type="password"/></td></tr>
        <tr><td></td><td><input type="submit" value="Login"></td></tr>
    </table>
</form>

        </td><td></td></tr>
    <tr><td><img src="<?php echo $this->baseUrl('images/a28.gif') ?>" alt=""/></td>
        <td></td>
        <td><img src="<?php echo $this->baseUrl('images/a29.gif') ?>" alt=""/></td></tr>
</table>