<form method="post" action="<?php echo $this->getUrl('login/index/process') ?>">
    <table>
        <tr><td><label for="email">E-Mail:</label></td><td><input name="email" id="email" type="text"/></td></tr>
        <tr><td><label for="password">Password:</label></td><td><input name="password" id="password" type="password"/></td></tr>
        <tr><td></td><td><input type="submit" value="Login"></td></tr>
    </table>
</form>
