<?php

$keyword = $this->keyword;

?>
<form method=post action="<?php echo $this->getUrl('*/*/save') ?>">
    <input type="hidden" name="id" value="<?php echo $keyword->query_id ?>" />
    <input type="hidden" name="campaign_id" value="<?php echo $this->campaign_id ?>" />
    <table>
        <tr><td><label for="query_q">Keyword:</label></td><td><input type="text" value="<?php echo $keyword->query_q ?>" name="query_q" id="query_q"/></td></tr>
        <tr><td><label for="query_lang">Locale:</label></td><td><select name="query_lang" id="query_lang"><?php echo $this->country_options ?></select></td></tr>
        <tr><td><label for="query_nearplace">Near this place:</label></td><td><input type="text" value="<?php echo $keyword->query_nearplace ?>" name="query_nearplace" id="query_nearplace"/></td></tr>
        <tr><td><label for="query_distance">Within</label> this <label for="query_distanceunit">distance</label>:</td>
            <td>
                <input type="text" value="<?php echo $keyword->query_distance ?>" name="query_distance" id="query_distance" size="9"/>
                <select name="query_distanceunit" id="query_distanceunit"><option value="mi">mi</option><option value="km"<?php echo $keyword->query_distanceunit == 'km' ? ' selected' : '' ?>>km</option></select>
            </td>
        </tr>
    </table><br />
    <div align="center"><input type=submit value="&nbsp; Save &nbsp;" class=bu> <input type=button value="Cancel" class=bu onclick="history.go(-1)"></div>
</form>